### ISSUE TITLE
How to export results from alphalens

### ISSUE THREAD

**Issue by Tigran26** [stefan-jansen/alphalens-reloaded#11]
Hello,

Can anyone tell me how to save and export output of alphalens. Particularly I am interested in tears.create_full_tear_sheet. Any help will be appreciates.

Thanks

**Comment by stefan-jansen** [comment]
The library is currently designed to display in the notebook. You could modify a local version of alphalens to call plt.savefig() instead of plt.show(), for instance. You could also add kwd arguments to add this option. PRs are welcome.

**Comment by Tigran26** [comment]
Thank you
