### ISSUE TITLE
AttributeError: 'Index' object has no attribute 'tz'

### ISSUE THREAD

**Issue by chen0126** [stefan-jansen/alphalens-reloaded#22]
## Problem Description

**Please provide a minimal, self-contained, and reproducible example:**
```python
result=al.utils.get_clean_factor_and_forward_returns(mv, price, quantiles=5, periods=(1,5,10))
```

**Please provide the full traceback:**
```python
File c:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\alphalens\utils.py:861, in get_clean_factor_and_forward_returns(factor, prices, groupby, binning_by_group, quantiles, bins, periods, filter_zscore, groupby_labels, max_loss, zero_aware, cumulative_returns)
    697 def get_clean_factor_and_forward_returns(
    698     factor,
    699     prices,
   (...)
    709     cumulative_returns=True,
    710 ):
    711     """
    712     Formats the factor data, pricing data, and group mappings into a DataFrame
    713     that contains aligned MultiIndex indices of timestamp and asset. The
   (...)
    858         For use when forward returns are already available.
    859     """
--> 861     forward_returns = compute_forward_returns(
    862         factor, prices, periods, filter_zscore, cumulative_returns
    863     )
    865     factor_data = get_clean_factor(
    866         factor,
    867         forward_returns,
   (...)
...
    287         "tz_convert."
    288     )
    290 freq = infer_trading_calendar(factor_dateindex, prices.index)

AttributeError: 'Index' object has no attribute 'tz'
```

**Please provide any additional information below:**

## Versions

* Alphalens version: 0.4.1
* Python version: 3.9.0
* Pandas version: 1.2.0
* Matplotlib version: 3.8.2

## Whole Pip List:

Package             Version
------------------- ------------
alphalens-reloaded  0.4.1
asttokens           2.4.1
certifi             2023.11.17
charset-normalizer  3.3.2
colorama            0.4.6
comm                0.2.0
contourpy           1.2.0
cycler              0.12.1
debugpy             1.8.0
decorator           5.1.1
empyrical           0.5.5
exceptiongroup      1.2.0
executing           2.0.1
fonttools           4.47.0
idna                3.6
importlib-metadata  7.0.1
importlib-resources 6.1.1
ipykernel           6.28.0
ipython             8.18.1
jedi                0.19.1
jupyter-client      8.6.0
jupyter-core        5.6.0
kiwisolver          1.4.5
lxml                4.9.4
matplotlib          3.8.2
matplotlib-inline   0.1.6
nest-asyncio        1.5.8
numpy               1.26.2
packaging           23.2
pandas              1.2.0
pandas-datareader   0.10.0
parso               0.8.3
patsy               0.5.5
Pillow              10.1.0
pip                 20.2.3
platformdirs        4.1.0
prompt-toolkit      3.0.43
psutil              5.9.7
pure-eval           0.2.2
pygments            2.17.2
pyparsing           3.1.1
python-dateutil     2.8.2
pytz                2023.3.post1
pywin32             306
pyzmq               25.1.2
requests            2.31.0
scipy               1.11.4
seaborn             0.13.0
setuptools          49.2.1
six                 1.16.0
stack-data          0.6.3
statsmodels         0.14.1
tornado             6.4
traitlets           5.14.0
typing-extensions   4.9.0
urllib3             2.1.0
wcwidth             0.2.12
zipp                3.17.0

**Comment by chen0126** [comment]
Linux without this error~~

**Comment by Frankgu3528** [comment]
same issue
