### ISSUE TITLE
why pricing = df.loc[:, 'Open'].iloc[1:].unstack('asset')?

### ISSUE THREAD

**Issue by quant2008** [stefan-jansen/alphalens-reloaded#23]
Hi, in this [tutorial](https://github.com/stefan-jansen/alphalens-reloaded/blob/main/docs/source/notebooks/overview.ipynb),it has:
`pricing = df.loc[:, 'Open'].iloc[1:].unstack('asset')`

I wonder why it exclude index 0. I think the following should be ok. anyone can correct me?
`pricing = df.loc[:, 'Open'].unstack('asset')`

**Comment by stefan-jansen** [comment]
The idea here is that only next day's open price would be available to trade on signals computed using today's close price.

**Comment by zh-qifan** [comment]
hmm...i think you should do shift(1) instead. That is, `pricing=df.groupby(level=(0,1)).shift(1)`. So if the signal is triggered on day T, we can only trade with price on day T+1 

If using `pricing = df.loc[:, 'Open'].iloc[1:].unstack('asset')`, it will only exclude the ticker A on 2015-06-02..
